/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as gasslessTokenSol from "./GasslessToken.sol";
export type { gasslessTokenSol };
export type { Counter } from "./Counter";
