/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../../common";
import type {
  MessageHashUtils,
  MessageHashUtilsInterface,
} from "../../../../../@openzeppelin/contracts/utils/cryptography/MessageHashUtils";

const _abi = [
  {
    inputs: [],
    name: "ERC5267ExtensionsNotSupported",
    type: "error",
  },
] as const;

const _bytecode =
  "0x6055604b600b8282823980515f1a607314603f577f4e487b71000000000000000000000000000000000000000000000000000000005f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea2646970667358221220032d2322421a6d1a84b9f48cd36e90e687cb208c4d13361c9cfb213628e6632c64736f6c634300081c0033";

type MessageHashUtilsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MessageHashUtilsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MessageHashUtils__factory extends ContractFactory {
  constructor(...args: MessageHashUtilsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<MessageHashUtils> {
    return super.deploy(overrides || {}) as Promise<MessageHashUtils>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): MessageHashUtils {
    return super.attach(address) as MessageHashUtils;
  }
  override connect(signer: Signer): MessageHashUtils__factory {
    return super.connect(signer) as MessageHashUtils__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MessageHashUtilsInterface {
    return new utils.Interface(_abi) as MessageHashUtilsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MessageHashUtils {
    return new Contract(address, _abi, signerOrProvider) as MessageHashUtils;
  }
}
